version: '3.6'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017
    DBcassandra:
        container_name: DBcassandra
        image: cassandra
        ports:
            - "8888:9042"  
        environment:
            -  CASSANDRA_RPC_ADDRESS=0.0.0.0
    apacheServer:
        container_name: apacheServer
        image: php:7.0-apache
        ports:
            - "8082:80"
        volumes:
            - ./htdocs:/var/www/html

    lighttpdServer:
        container_name: lighttpdServer
        image: thibremy/lighttpd-php
        ports:
            - "8081:80"
        volumes:
            - ./lumen:/var/www/localhost/htdocs

    nginxServer:
        container_name: nginxServer
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
            - DBcassandra
            - mongodb
    php:
        image: php:7-fpm
        volumes:
            - ./code:/code
